import 'dart:io';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:haus_des_control/Modules/inspector/widgets/custom_toast.dart';
import '../../../models/document_model.dart';
import '../admin_firebase_services/admin_document_service.dart';

class AdminDocumentsProvider extends ChangeNotifier {
  final AdminDocumentService _service = AdminDocumentService();

  List<DocumentModel> _documents = [];
  List<DocumentModel> get documents => _documents;

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  bool _isUploading = false;
  bool get isUploading => _isUploading;

  String? _errorMessage;
  String? get errorMessage => _errorMessage;

  DocumentSnapshot? _lastDocument;
  bool _hasMore = true;
  bool get hasMore => _hasMore;

  String? _currentBranchId;
  String? get currentBranchId => _currentBranchId;

  // Load documents for a specific branch
  Future<void> loadBranchDocuments(
    String branchId, {
    bool refresh = false,
  }) async {
    // If switching branches or refreshing, reset everything
    if (_currentBranchId != branchId || refresh) {
      _documents = [];
      _lastDocument = null;
      _hasMore = true;
      _currentBranchId = branchId;
    }

    // Don't load if already loading or no more documents
    if (_isLoading || !_hasMore) return;

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final result = await _service.getDocuments(
        branchId: branchId,
        pageSize: 20,
        lastDocument: _lastDocument,
      );

      _documents.addAll(result['documents'] as List<DocumentModel>);
      _lastDocument = result['lastDocument'];
      _hasMore = result['hasMore'] as bool;
    } catch (e) {
      _errorMessage = e.toString();
      debugPrint('Error loading documents: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Load more documents (pagination)
  Future<void> loadMoreDocuments() async {
    if (_currentBranchId != null && !_isLoading && _hasMore) {
      await loadBranchDocuments(_currentBranchId!);
    }
  }

  // Refresh documents (pull to refresh)
  Future<void> refreshDocuments() async {
    if (_currentBranchId != null) {
      await loadBranchDocuments(_currentBranchId!, refresh: true);
    }
  }

  // Upload and add new document
  Future<bool> uploadDocument({
    required File file,
    required String fileName,
    required String name,
    required String description,
    required String branchId,
    required String uploadedBy,
    required String uploadedByName,
    required BuildContext context,
  }) async {
    _isUploading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      // Validate file size (max 10MB)
      final fileSize = await file.length();
      if (fileSize > 10 * 1024 * 1024) {
        throw Exception('File size must be less than 10MB');
      }

      // Get file extension
      final fileExtension = fileName.split('.').last.toLowerCase();

      // Validate file extension
      const allowedExtensions = ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt'];
      if (!allowedExtensions.contains(fileExtension)) {
        throw Exception(
          'Invalid file type. Allowed: ${allowedExtensions.join(", ")}',
        );
      }

      // Upload file to storage
      final uploadResult = await _service.uploadFile(file, fileName, branchId);

      // Create document model
      final document = DocumentModel(
        id: '', // Will be generated by Firestore
        branchId: branchId,
        name: name,
        description: description,
        fileUrl: uploadResult['fileUrl']!,
        fileName: fileName,
        fileSize: fileSize,
        fileExtension: fileExtension,
        uploadedAt: DateTime.now(),
        uploadedBy: uploadedBy,
        uploadedByName: uploadedByName,
      );

      // Add document to Firestore
      final docId = await _service.addDocument(document);

      // Create complete document with ID
      final newDocument = DocumentModel(
        id: docId,
        branchId: document.branchId,
        name: document.name,
        description: document.description,
        fileUrl: document.fileUrl,
        fileName: document.fileName,
        fileSize: document.fileSize,
        fileExtension: document.fileExtension,
        uploadedAt: document.uploadedAt,
        uploadedBy: document.uploadedBy,
        uploadedByName: document.uploadedByName,
      );

      // Add to local list at the beginning
      _documents.insert(0, newDocument);
      _isUploading = false;
      notifyListeners();

      if (context.mounted) {
        showSnakBarr(context, 'Document uploaded successfully!');
      }

      return true;
    } catch (e) {
      _errorMessage = e.toString();
      _isUploading = false;
      notifyListeners();

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Upload failed: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
      return false;
    }
  }

  // Delete document
  Future<bool> deleteDocument(
    String documentId,
    String fileUrl, {
    required BuildContext context,
  }) async {
    if (_currentBranchId == null) return false;

    // Store document for potential rollback
    final documentIndex = _documents.indexWhere((d) => d.id == documentId);
    if (documentIndex == -1) return false;

    final deletedDocument = _documents[documentIndex];

    // Optimistically remove from list
    _documents.removeAt(documentIndex);
    notifyListeners();

    try {
      await _service.deleteDocument(_currentBranchId!, documentId, fileUrl);

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Document deleted successfully'),
            backgroundColor: Colors.green,
          ),
        );
      }

      return true;
    } catch (e) {
      // Rollback on error
      _documents.insert(documentIndex, deletedDocument);
      _errorMessage = e.toString();
      notifyListeners();

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error deleting document: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
      return false;
    }
  }

  // Update document metadata (name, description)
  Future<bool> updateDocument(
    String documentId,
    Map<String, dynamic> updates, {
    required BuildContext context,
  }) async {
    if (_currentBranchId == null) return false;

    try {
      await _service.updateDocument(_currentBranchId!, documentId, updates);

      // Update local list
      final index = _documents.indexWhere((d) => d.id == documentId);
      if (index != -1) {
        // Refresh the document from server to get updated data
        final updatedDoc = await _service.getDocument(
          _currentBranchId!,
          documentId,
        );
        if (updatedDoc != null) {
          _documents[index] = updatedDoc;
          notifyListeners();
        }
      }

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Document updated successfully'),
            backgroundColor: Colors.green,
          ),
        );
      }

      return true;
    } catch (e) {
      _errorMessage = e.toString();
      notifyListeners();

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error updating document: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
      return false;
    }
  }

  // Search documents
  Future<void> searchDocuments(String query) async {
    if (_currentBranchId == null) return;

    if (query.trim().isEmpty) {
      // If query is empty, reload all documents
      await refreshDocuments();
      return;
    }

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _documents = await _service.searchDocuments(_currentBranchId!, query);
      _hasMore = false; // Disable pagination for search results
    } catch (e) {
      _errorMessage = e.toString();
      debugPrint('Error searching documents: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Get document by ID
  Future<DocumentModel?> getDocumentById(String documentId) async {
    if (_currentBranchId == null) return null;

    try {
      // First check local list
      final localDoc = _documents.firstWhere(
        (doc) => doc.id == documentId,
        orElse: () => DocumentModel(
          id: '',
          branchId: '',
          name: '',
          description: '',
          fileUrl: '',
          fileName: '',
          fileSize: 0,
          fileExtension: '',
          uploadedAt: DateTime.now(),
          uploadedBy: '',
          uploadedByName: '',
        ),
      );

      if (localDoc.id.isNotEmpty) return localDoc;

      // If not found locally, fetch from server
      return await _service.getDocument(_currentBranchId!, documentId);
    } catch (e) {
      _errorMessage = e.toString();
      debugPrint('Error getting document: $e');
      return null;
    }
  }

  // Get document count
  int getDocumentCount() => _documents.length;

  // Check if a document exists locally
  bool hasDocument(String documentId) {
    return _documents.any((doc) => doc.id == documentId);
  }

  // Get documents by file type
  List<DocumentModel> getDocumentsByType(String fileExtension) {
    return _documents
        .where(
          (doc) =>
              doc.fileExtension.toLowerCase() == fileExtension.toLowerCase(),
        )
        .toList();
  }

  // Get recent documents (last N days)
  List<DocumentModel> getRecentDocuments(int days) {
    final cutoffDate = DateTime.now().subtract(Duration(days: days));
    return _documents
        .where((doc) => doc.uploadedAt.isAfter(cutoffDate))
        .toList();
  }

  // Calculate total storage used
  int getTotalStorageUsed() {
    return _documents.fold(0, (sum, doc) => sum + doc.fileSize);
  }

  // Get formatted total storage
  String getFormattedTotalStorage() {
    final totalBytes = getTotalStorageUsed();
    if (totalBytes < 1024) return '$totalBytes B';
    if (totalBytes < 1024 * 1024) {
      return '${(totalBytes / 1024).toStringAsFixed(2)} KB';
    }
    if (totalBytes < 1024 * 1024 * 1024) {
      return '${(totalBytes / (1024 * 1024)).toStringAsFixed(2)} MB';
    }
    return '${(totalBytes / (1024 * 1024 * 1024)).toStringAsFixed(2)} GB';
  }

  // Clear error message
  void clearError() {
    _errorMessage = null;
    notifyListeners();
  }

  // Clear provider and reset state
  void clear() {
    _documents = [];
    _lastDocument = null;
    _hasMore = true;
    _currentBranchId = null;
    _errorMessage = null;
    _isLoading = false;
    _isUploading = false;
    notifyListeners();
  }

  // Dispose
  @override
  void dispose() {
    _documents.clear();
    super.dispose();
  }
}
